server {
    listen 2020;
    root ./www;

    location / {
        root ./www;
    }

    location /upload {
        root ./uploads;
        allowed_methods POST;
    }
}

server ze {
    listen 8080;
    root ./www;

    location / {
        root ./www;
    }
   location /upload {
        root ./uploads;
        allowed_methods POST;
    }
}
